package conversation

import("context";"errors";"fmt";"sort";"github.com/google/uuid";"gorm.io/gorm";"gorm.io/gorm/clause")
var(ErrUnavailable=errors.New("conversation repository unavailable");ErrNotFound=errors.New("conversation not found");ErrForbidden=errors.New("conversation membership required");ErrSelfChat=errors.New("cannot chat with yourself"))
type Repository interface{Direct(context.Context,uuid.UUID,uuid.UUID)(*Conversation,error);List(context.Context,uuid.UUID)([]ConversationSummary,error);Messages(context.Context,uuid.UUID,uuid.UUID)([]Message,error);Post(context.Context,*Message)error;Read(context.Context,uuid.UUID,uuid.UUID)error;Unread(context.Context,uuid.UUID)(int64,error)}
type GormRepository struct{db *gorm.DB};func NewGormRepository(db *gorm.DB)*GormRepository{return &GormRepository{db:db}}
func directKey(a,b uuid.UUID)string{v:=[]string{a.String(),b.String()};sort.Strings(v);return v[0]+":"+v[1]}
func(r *GormRepository)Direct(ctx context.Context,me,peer uuid.UUID)(*Conversation,error){if r.db==nil{return nil,ErrUnavailable};if me==peer{return nil,ErrSelfChat};var out Conversation;err:=r.db.WithContext(ctx).Transaction(func(tx *gorm.DB)error{var count int64;if err:=tx.Table("users").Where("id=?",peer).Count(&count).Error;err!=nil{return mapError(err)};if count==0{return ErrNotFound};key:=directKey(me,peer);candidate:=Conversation{Kind:"direct",DirectKey:key};if err:=tx.Clauses(clause.OnConflict{Columns:[]clause.Column{{Name:"direct_key"}},DoNothing:true}).Create(&candidate).Error;err!=nil{return mapError(err)};if err:=tx.Where("direct_key=?",key).First(&out).Error;err!=nil{return mapError(err)};for _,uid:=range[]uuid.UUID{me,peer}{if err:=tx.Exec("INSERT INTO conversation_members (conversation_id,user_id) VALUES (?,?) ON CONFLICT DO NOTHING",out.ID,uid).Error;err!=nil{return mapError(err)}};return nil});return &out,err}
type listRow struct{Conversation;PeerID uuid.UUID;PeerNickname string;PeerSchool string;UnreadCount int64}
func(r *GormRepository)List(ctx context.Context,uid uuid.UUID)([]ConversationSummary,error){if r.db==nil{return nil,ErrUnavailable};var rows []listRow;err:=r.db.WithContext(ctx).Table("conversations c").Select("c.*, u.id AS peer_id, u.nickname AS peer_nickname, u.school AS peer_school, (SELECT COUNT(*) FROM direct_messages dm WHERE dm.conversation_id=c.id AND dm.sender_id<>? AND (mine.last_read_at IS NULL OR dm.created_at>mine.last_read_at)) AS unread_count",uid).Joins("JOIN conversation_members mine ON mine.conversation_id=c.id AND mine.user_id=?",uid).Joins("JOIN conversation_members other ON other.conversation_id=c.id AND other.user_id<>?",uid).Joins("JOIN users u ON u.id=other.user_id").Order("COALESCE(c.last_message_at,c.created_at) DESC").Scan(&rows).Error;if err!=nil{return nil,mapError(err)};out:=make([]ConversationSummary,0,len(rows));for _,x:=range rows{out=append(out,ConversationSummary{Conversation:x.Conversation,Peer:UserSummary{ID:x.PeerID,Nickname:x.PeerNickname,School:x.PeerSchool},UnreadCount:x.UnreadCount})};return out,nil}
func(r *GormRepository)member(ctx context.Context,cid,uid uuid.UUID)error{var n int64;if err:=r.db.WithContext(ctx).Table("conversation_members").Where("conversation_id=? AND user_id=?",cid,uid).Count(&n).Error;err!=nil{return mapError(err)};if n==0{return ErrForbidden};return nil}
type messageRow struct{Message;SenderNickname string;SenderSchool string}
func(r *GormRepository)Messages(ctx context.Context,cid,uid uuid.UUID)([]Message,error){if r.db==nil{return nil,ErrUnavailable};if err:=r.member(ctx,cid,uid);err!=nil{return nil,err};var rows []messageRow;err:=r.db.WithContext(ctx).Table("direct_messages m").Select("m.*,u.nickname AS sender_nickname,u.school AS sender_school").Joins("JOIN users u ON u.id=m.sender_id").Where("m.conversation_id=?",cid).Order("m.created_at").Limit(100).Scan(&rows).Error;if err!=nil{return nil,mapError(err)};out:=make([]Message,0,len(rows));for _,x:=range rows{x.Message.Sender=UserSummary{ID:x.SenderID,Nickname:x.SenderNickname,School:x.SenderSchool};out=append(out,x.Message)};return out,nil}
func(r *GormRepository)Post(ctx context.Context,m *Message)error{if r.db==nil{return ErrUnavailable};if err:=r.member(ctx,m.ConversationID,m.SenderID);err!=nil{return err};return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB)error{if err:=tx.Create(m).Error;err!=nil{return mapError(err)};return mapError(tx.Model(&Conversation{}).Where("id=?",m.ConversationID).Updates(map[string]any{"last_message_at":m.CreatedAt,"updated_at":gorm.Expr("NOW()")}).Error)})}
func(r *GormRepository)Read(ctx context.Context,cid,uid uuid.UUID)error{if r.db==nil{return ErrUnavailable};if err:=r.member(ctx,cid,uid);err!=nil{return err};result:=r.db.WithContext(ctx).Exec("UPDATE conversation_members SET last_read_at=NOW() WHERE conversation_id=? AND user_id=?",cid,uid);return mapError(result.Error)}
func(r *GormRepository)Unread(ctx context.Context,uid uuid.UUID)(int64,error){if r.db==nil{return 0,ErrUnavailable};var n int64;err:=r.db.WithContext(ctx).Raw("SELECT COUNT(*) FROM direct_messages dm JOIN conversation_members cm ON cm.conversation_id=dm.conversation_id AND cm.user_id=? WHERE dm.sender_id<>? AND (cm.last_read_at IS NULL OR dm.created_at>cm.last_read_at)",uid,uid).Scan(&n).Error;return n,mapError(err)}
func mapError(err error)error{if err==nil{return nil};if errors.Is(err,gorm.ErrRecordNotFound){return ErrNotFound};return fmt.Errorf("conversation repository: %w",err)}
